tomerge:
  FALSE
resourcesfolder:
  ../resources/
resultsfolder:
  ../results/
fastqfiles:
  - DRYER_natura
#mergedfile:
#   DRYER_natura_merged
split_fastq:
  nfiles: 500
alifilt:
  minscore: 40.00
split_fasta:
  nfiles: 2
basicfilt:
  minlength: 80
  mincount: 1
clustering:
  minsim: 0.97
