---
title: "ITS_analyses"
author: "Marion Boisseaux"
date: "2023-04-27"
output: html_document
---

```{r main libraries, results='hide'}
library(tidyverse)
library(dplyr)
library(FactoMineR)
library(car)
library(missMDA)
library(metabaR)
library(ggplot2)
library(corrplot)
library(factoextra)
library(MASS)
library(cowplot)
library(nlme)
library(MuMIn)
library(multcomp)
library(ggpubr)
library(ade4)
library(hillR)
library(adespatial)
library(reldist)
library(bipartite)
library(vegan)
library(scales)
library(phyloseq)
library(reshape2)
library(ggpubr)

library(BiocManager)
#BiocManager::install("microbiome")
library(microbiome)  
```

# ITS - Leaf

```{r}
#only leaf
load("./resources/Metabarlist_natura_clean_ITS2.Rdata")
leaf <- subset_metabarlist(natura_clean, table = "samples",
                          indices = natura_clean$samples$organ == "leaf")
save(leaf, file = "./results/Metabarlist_natura_clean_16S_leaf.Rdata")
```

## alpha diversity


```{r}
library(vegan)

dim(leaf$reads) #species = OTUS et sites = mes plantules/samples 

Richness <- specnumber(x = leaf$reads)
H <- vegan::diversity(x = leaf$reads, index = "shannon") #The default is to use natural logarithms. But if base = 2, it has theoretical justification. takes into account species abundance and evenness
D1 <- vegan::diversity(x = leaf$reads, index = "simpson")
D2 <- vegan::diversity(x = leaf$reads, index = "invsimpson", base = 2)
J <- H/log(specnumber(x = leaf$reads)) #Pielou’s evenness 

#Rényi entropy & Hill's numbers

R <- renyi(leaf$reads, scales = 2)
head(R)
N2 <- renyi(leaf$reads, scales = 2, hill = TRUE)  # other way to calculte inverse simpson
head(N2)
k <- sample(nrow(leaf$reads), 6)
R <- renyi(leaf$reads[k,])
plot(R)


#Differences in species richness across samples
df <- Richness %>% 
  enframe() %>%
  rename(Richness = value, 
         sample_id = name)

df2 <- left_join(leaf$samples, df)

plot_richness <- ggplot(df2, aes(x = name, y = Richness, fill = name)) +
  geom_boxplot() +
  labs(title = "Species richness - ITS leaf")+
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())
plot_richness

#looking at shannon
df <- H %>% 
  enframe() %>%
  rename(Shannon = value, 
         sample_id = name)

df2 <- left_join(df2, df)

plot_shannon <- ggplot(df2, aes(x = name, y = Shannon, fill = name)) +
  geom_boxplot() +
  labs(title = "Shannon - ITS leaf")+
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())

plot_shannon

#look at invsimpson
df <- D2 %>% 
  enframe() %>%
  rename(invSimpson= value, 
         sample_id = name)

df2 <- left_join(df2, df)

plot_invS <- ggplot(df2, aes(x = name, y = invSimpson, fill = name)) +
  geom_boxplot() +
  labs(title = "InvSimpson - ITS leaf") +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())
plot_invS


#look at the same time Richness, shannon and inv_simpson per species

r <- ggarrange(plot_richness, plot_shannon, plot_invS, ncol = 1, nrow = 3, common.legend = TRUE, legend = "bottom")
r

ggsave("./results/ITS_leaf_a_diversity.jpeg", r)

```

# ITS - Root

```{r}
#only roots
load("./resources/Metabarlist_natura_clean_ITS2.Rdata")
root <- subset_metabarlist(natura_clean, table = "samples",
                          indices = natura_clean$samples$organ == "root")
save(root, file = "./results/Metabarlist_natura_clean_16S_root.Rdata")
```

## alpha diversity


```{r}
library(vegan)

dim(root$reads) #species = OTUS et sites = mes plantules/samples 

Richness <- specnumber(x = root$reads)
H <- vegan::diversity(x = root$reads, index = "shannon") #The default is to use natural logarithms. But if base = 2, it has theoretical justification. takes into account species abundance and evenness
D1 <- vegan::diversity(x = root$reads, index = "simpson")
D2 <- vegan::diversity(x = root$reads, index = "invsimpson", base = 2)
J <- H/log(specnumber(x = root$reads)) #Pielou’s evenness 

#Rényi entropy & Hill's numbers

R <- renyi(root$reads, scales = 2)
head(R)
N2 <- renyi(root$reads, scales = 2, hill = TRUE)  # other way to calculte inverse simpson
head(N2)
k <- sample(nrow(root$reads), 6)
R <- renyi(root$reads[k,])
plot(R)


#Differences in species richness across samples
df <- Richness %>% 
  enframe() %>%
  rename(Richness = value, 
         sample_id = name)

df2 <- left_join(root$samples, df)

plot_richness <- ggplot(df2, aes(x = name, y = Richness, fill = name)) +
  geom_boxplot() +
  labs(title = "Species richness - ITS root")+
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())
plot_richness

#looking at shannon
df <- H %>% 
  enframe() %>%
  rename(Shannon = value, 
         sample_id = name)

df2 <- left_join(df2, df)

plot_shannon <- ggplot(df2, aes(x = name, y = Shannon, fill = name)) +
  geom_boxplot() +
  labs(title = "Shannon - ITS root")+
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())

plot_shannon

#look at invsimpson
df <- D2 %>% 
  enframe() %>%
  rename(invSimpson= value, 
         sample_id = name)

df2 <- left_join(df2, df)

plot_invS <- ggplot(df2, aes(x = name, y = invSimpson, fill = name)) +
  geom_boxplot() +
  labs(title = "InvSimpson - ITS root") +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())
plot_invS


#look at the same time Richness, shannon and inv_simpson per species

r <- ggarrange(plot_richness, plot_shannon, plot_invS, ncol = 1, nrow = 3, common.legend = TRUE, legend = "bottom")
r

ggsave("./results/ITS_root_a_diversity.jpeg", r)

```



## beta diversity

 how similar in microbial composition each sample is to other samples of different types, or between sample variability.

```{r}
# calculate Bray-Curtis distance using the vegan package
#Microbiota data are sparse and specific distances, such as Bray-Curtis, Jaccard or weight/unweight Unifrac distances, better deal with the problem of the presence of many double zeros in data sets.
dist_bc <- as.matrix(vegdist(root$reads, method = "bray"))

essai <- dist_bc %>% 
  enframe()
library(MASS)
set.seed(123456)

birds_nmds <- metaMDS(decostand(root$reads, method = "hellinger"),
    dist = "bray",
    autotransform = FALSE, expand = FALSE, )

birds_nmds

stressplot(birds_nmds)

#check dimensionality k
k_vec <- 1:10
stress <- numeric(length(k_vec))
birds_dij <-metaMDSdist(root$reads)
set.seed(25)
for(i in seq_along(k_vec)) {
    sol <- metaMDSiter(birds_dij, k = i,
                       trace = TRUE)
    stress[i] <- sol$stress
}

plot(k_vec, stress, type = "b", ylab = "Stress",
     xlab = "Dimensions")

#adding supplementary variables to explain the data
ordipointlabel(birds_nmds)
ev_nmds <- envfit(birds_nmds ~ name, data = root$samples)
ev_nmds

plot(ev_nmds, add = TRUE)

ordisurf(birds_nmds ~ Altit, data = birds_env, add = TRUE)
```



```{r}
## Import packages and data
library("phyloseq")
library("ggplot2")

data("GlobalPatterns")

## Create function
beta_boxplot <- function(physeq, method = "bray", group) {

  # physeq: phyloseq-class object
  # method: beta-diversity metric. Default "bray", i.e., Bray-Curtis dissimilarity 
  # group: factorial variable to group

  ## Packages
  require("phyloseq") # v.1.30.0
  require("ggplot2") # v.3.3.2

  ## Identify the correspondence: group and samples
  group2samp <- list() # list to save the correspondence between group <--> samples
  group_list <- get_variable(sample_data(physeq), group) # list of group elements
  for (groups in levels(group_list)) { # loop over the no. of group levels
    target_group <- which(group_list == groups) # vct pos of the curr group variable 
    group2samp[[ groups ]] <- sample_names(physeq)[target_group] # matching samples: based on vct pos
  }  

  ## Calculate beta-diversity
  beta_div_dist <- distance(physeq = physeq, method = method)
  beta_div_dist <- as(beta_div_dist, "matrix")

  ## Coerce distance mtx into a tidy data frame by group
  dist_df <- data.frame() # save results in df 
  counter <- 1 
  for (groups in names(group2samp)) { # loop over group fct levels 
    sub_dist <- beta_div_dist[ group2samp[[groups]], group2samp[[groups]] ] # subset dist mtx to curr samples
    #print(sub_dist)
    no_samp_col <- ncol(sub_dist) # n cols: curr sub dist
    no_samp_row <- nrow(sub_dist) # n rows: curr sub dist
    for ( cols in seq(no_samp_col) ) { # loop over cols: curr sub_dist
      if ( cols > 1 ) {
        for ( rows in seq((cols-1)) ) { # loop over rows: curr sub_dist 
          ## Save results
          dist_df[ counter, "sample_pair" ] <- paste0( colnames(sub_dist)[cols], "-",  
                                                       rownames(sub_dist)[rows] ) # sample pair
          dist_df[ counter, "group" ] <- groups # group  
          dist_df[ counter, "beta_div_method" ] <- method # method
          dist_df[ counter, "beta_div_value" ] <- sub_dist[rows, cols] # beta-diversity for the sample pair     
         counter = counter + 1
        }
      }
    }
  }

  ## Create a ggplot2 boxplot
  plot_boxplot <- ggplot(data = dist_df, aes(x = group, y = beta_div_value, color = group)) + 
    geom_boxplot(outlier.shape=NA) +
    geom_jitter() + 
    theme_bw() + 
    xlab(group) + ylab(method) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

  ## Save df and boxplot into a list 
  list_Out <- list("data" = dist_df, "plot" = plot_boxplot) 

  return(list_Out)
}

## Test function 
beta_boxplot_result <- beta_boxplot(physeq = GlobalPatterns, method = "bray", group = "SampleType")

## Data
beta_boxplot_result$data

## Plot
beta_boxplot_result$plot
```
